import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import profile from "../../public/profile.png";
import gorent from "../../public/gorent.png";
import kitabantuin from "../../public/kitabantuin.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          {/* Navbar */}
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-burtons text-xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r bg-gradient-to-r from-sky-400 to-blue-500">My Portfolio</h1>
            <ul className="flex items-center">
              {/* <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li> */}
              <li>
                <a
                  className="bg-gradient-to-r bg-gradient-to-r from-sky-400 to-blue-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-sky-600 font-medium dark:text-sky-400 md:text-6xl">
              Firgi Sotya Izzuddin
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Fullstack Web Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
              <a href="" target="_blank">

              <AiFillLinkedin />
              </a>
              <a href="https://github.com/Firgisotya" target="_blank">

              <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-sky-400 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={profile} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, I've
              done remote work for
              <span className="text-sky-400"> agencies </span>
              consulted for <span className="text-sky-400">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, programming.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                My Skills
              </h3>
              <p className="py-2">
                Here are the programming skills that I mastered.
              </p>
              <h4 className="py-4 text-sky-600">Programming Skills I Mastered</h4>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">Node Js</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">React Js</p>
              <p className="text-gray-800 py-1">Angular</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-sky-600">Programming Tools I Use</h4>
              <p className="text-gray-800 py-1">Vscode</p>
              <p className="text-gray-800 py-1">Xampp</p>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">Sublime Text</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-sky-600">Consult With Me Regarding</h4>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">React Js</p>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">Node Js</p>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, I've
              done remote work for
              <span className="text-sky-400"> agencies </span>
              consulted for <span className="text-sky-400">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, programming.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://gorent.trixsite.com" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={gorent}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://kitabantuin.trixsite.com" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={kitabantuin}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
